[parity]
chain = "/Users/psum399a/ewf/chain.json"
base_path = "~/ewf/.local/share/io.parity.ethereum"
db_path = "~/ewf/.local/share/io.parity.ethereum/chains"
keys_path = "~/ewf/.local/share/io.parity.ethereum/keys"
identity = ""
light = false
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "none"
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

[ui]
force = false
disable = false
port = 8180
interface = "0.0.0.0"
path = "~/ewf/.local/share/io.parity.ethereum/signer"

[rpc]
disable = false
port = 8545
interface = "0.0.0.0"
cors = "null"
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[websockets]
disable = false
port = 8546
interface = "0.0.0.0"
origins = ["none"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[ipc]
disable = true
path = "~/ewf/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]

[dapps]
disable = false
path = "~/ewf/.local/share/io.parity.ethereum/dapps"

[secretstore]
disable = false
nodes = []
http_interface = "0.0.0.0"
http_port = 8082
interface = "0.0.0.0"
port = 8083
path = "~/ewf/.local/share/io.parity.ethereum/secretstore"

[ipfs]
enable = false
port = 5001
interface = "0.0.0.0"
cors = "null"
hosts = ["none"]

[network]
port = 30303
min_peers = 25
max_peers = 50
nat = "any"
id = 1
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_only = false
bootnodes = ["enode://147573f46fe9f5cc38fbe070089a31390baec5dd2827c8f2ef168833e4d0254fbee3969a02c5b9910ea5d5b23d86a6ed5eabcda17cc12007b7d9178b6c697aa5@ewf.slock.it:30303"]

[account]
keys_iterations = 10240

[footprint]
tracing = "auto"
pruning = "auto"
pruning_history = 64
pruning_memory = 500
cache_size_db = 64
cache_size_blocks = 8
cache_size_queue = 50
cache_size_state = 25
cache_size = 128 # Overrides above caches with total size
fast_and_loose = false
db_compaction = "ssd"
fat_db = "auto"
scale_verifiers = true
num_verifiers = 6

[snapshots]
disable_periodic = false

[vm]
jit = false

[misc]
logging = "own_tx=trace"
log_file = "/Users/psum399a/ewf/parity.log"
color = true

[mining]
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
work_queue_size = 20
relay_set = "cheap"
usd_per_tx = "0.0025"
usd_per_eth = "auto"
price_update_period = "hourly"
gas_floor_target = "4700000"
gas_cap = "6283184"
tx_queue_size = 8192
tx_queue_gas = "off"
tx_queue_strategy = "gas_factor"
tx_queue_ban_count = 1
tx_queue_ban_time = 180 #s
tx_gas_limit = "6283184"
tx_time_limit = 100 #ms
extra_data = "Parity"
remove_solved = false
notify_work = ["http://localhost:3001"]
refuse_service_transactions = false
